name: CommandLogger
version: 0.4
description: Logs all commands in minecraft console and player
author: The_Toyz
website: http://toyz.ninja

main: com.toyz.CommandLogger.CommandLogger

commands:
   coml:
     description: Gets the about information of the plugin

permissions:
   coml.purge:
     description: Allows the user to purge the logs
   coml.backup:
     description: Allows a staff member to purge and back-up logs
  
